dist: precise
stages:
  - name: build
addons:
  apt:
    packages:
      - ia32-libs
      - libc6-dev-i386
      - linux-headers-generic
      - libstdc++5
      - g++-multilib
      - gcc-multilib

jobs:
  include:
    - stage: build
      name: 'Build'
      script:
        - export LIBRARY_PATH=/usr/lib/$(gcc -print-multiarch)
        - export C_INCLUDE_PATH=/usr/include/$(gcc -print-multiarch)
        - export CPLUS_INCLUDE_PATH=/usr/include/$(gcc -print-multiarch)
        - sudo ln -s /usr/include/asm-generic /usr/include/asm
        - ./configure
        - make
        - make install
