dist: precise
before_install:
  # Install and manage Debian Lenny packages (Ubuntu Precise is too new)
  - sudo add-apt-repository 'deb http://archive.debian.org/debian-archive/debian/ lenny main contrib'
  - sudo add-apt-repository 'deb http://archive.debian.org/debian-security/ lenny/updates main contrib'
stages:
  - name: build
addons:
  apt:
    packages:
      - ia32-libs
      - libc6-dev-i386
jobs:
  include:
    - stage: build
      name: 'Build'
      script:
        - export LIBRARY_PATH=/usr/lib/$(gcc -print-multiarch)
        - export C_INCLUDE_PATH=/usr/include/$(gcc -print-multiarch)
        - export CPLUS_INCLUDE_PATH=/usr/include/$(gcc -print-multiarch)
        - ./configure
        - make
        - make install
